package loan

import (
	"errors"
	"time"
)

// Status represents the lifecycle of a loan record.
type Status string

const (
	StatusActive   Status = "ACTIVE"
	StatusReturned Status = "RETURNED"
)

// Loan is the core domain object, mirroring the loans table.
type Loan struct {
	ID         string
	RequestID  string // idempotency key generated by library-service
	UserID     string
	BookID     string
	Status     Status
	LoanedAt   time.Time
	ReturnedAt *time.Time // nil until the loan is returned
}

// Sentinel errors — returned as values, never panicked.
var (
	ErrNotFound           = errors.New("loan not found")
	ErrAlreadyReturned    = errors.New("loan is already returned")
	ErrDuplicateRequestID = errors.New("a loan with this request_id already exists")
	// ErrBookReleaseFailed signals that the loan was persisted as RETURNED but
	// the subsequent call to library-service to release the book copy failed.
	// Local state is NOT rolled back; the caller must handle the retry.
	ErrBookReleaseFailed = errors.New("book release failed after loan was marked returned")
)
